test(eslint): Specify the absolute path

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -39,7 +39,9 @@ jobs:
         env:
           SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
         run: |
-          npx eslint ./src --config ./eslint.config.json --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif || echo "ESLint run failed"
+          CONFIG_PATH=$(pwd)/eslint.config.json
+          echo "Using ESLint Config: $CONFIG_PATH"
+          npx eslint src/ --config $CONFIG_PATH --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif || echo "ESLint run failed"
         continue-on-error: true
 
       - name: Verify eslint-results.sarif creation
